openapi: 3.0.0
info:
  description: "This is a simple api that allows you to store and view UK mountains"
  version: 0.0.1
  title: UK Mountain API
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: mountains
    description: Everything about uk mountain
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /mountains:
    post:
      tags:
        - mountains
      summary: Add a new mountain to the listing
      description: ""
      operationId: addMountain
      requestBody:
        $ref: "#/components/requestBodies/Mountain"
      responses:
        "405":
          description: Invalid input
    get:
      tags:
        - mountains
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: listMountains
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mountain"
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mountain"
        "400":
          description: Invalid status value
  "/mountains/{mountain_id}":
    get:
      tags:
        - mountains
      summary: Find mountain by ID
      description: Returns a single pet
      operationId: getMountainById
      parameters:
        - name: mountain_id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64 
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Mountain"
            application/json:
              schema:
                $ref: "#/components/schemas/Mountain"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
servers:
  - url: https://petstore.swagger.io/v2
components:
  requestBodies:
    Mountain:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Mountain"
        application/xml:
          schema:
            $ref: "#/components/schemas/Mountain"
      description: Pet object that needs to be added to the store
      required: true
  schemas:
    Mountain:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Scaffel Pike
        Region:
          type: string
          example: Lake District - South West
        metres:
          type: number
          format: int64
          example: 978
      xml:
        name: Mountain